{% set name = "scheduler" %}
{% set version = "0.8.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scheduler-{{ version }}.tar.gz
  sha256: 7b20f9e9ec37c9ac17d22582a6c9693743fd75edabaef9ada21d3f8a9499eaf1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - typeguard >=3.0.0

test:
  imports:
    - scheduler
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DigonIO/scheduler
  summary: A simple in-process python scheduler library with asyncio, threading and timezone support.
  license: LGPL-3.0
  license_file: LICENSE
  doc_url: https://digon.io/hyd/project/scheduler/t/master/


extra:
  recipe-maintainers:
    - sanurielf
