{% set name = "scheduler" %}
{% set version = "0.8.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scheduler-{{ version }}.tar.gz
  sha256: 0093cad8c8957552fa8c4cb002b900daf731b26c2a7179f2f3e2bd1b6bf02c4f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - typeguard >=3.0.0

test:
  imports:
    - scheduler
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DigonIO/scheduler
  summary: A simple in-process python scheduler library with asyncio, threading and timezone support.
  license: LGPL-3.0
  license_file: LICENSE
  doc_url: https://digon.io/hyd/project/scheduler/t/master/


extra:
  recipe-maintainers:
    - sanurielf
