{% set name = "scheduler" %}
{% set version = "0.8.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scheduler-{{ version }}.tar.gz
  sha256: b2234a069448a617abbc511b9e18f48c4deb3dcd9dcc51721d9c90ef2943b72a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - typeguard >=3.0.0

test:
  imports:
    - scheduler
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DigonIO/scheduler
  summary: A simple in-process python scheduler library with asyncio, threading and timezone support.
  license: LGPL-3.0
  license_file: LICENSE
  doc_url: https://digon.io/hyd/project/scheduler/t/master/


extra:
  recipe-maintainers:
    - sanurielf
